### ISSUE TITLE
Still functional ?

### ISSUE THREAD

**Issue by asvt** [ComFoxx/calameo-download-pdf#1]
Hello, 

Could you check if the page is still functional? A priori, it is no longer so.

Thank you so much for sharing your code, it has already helped me a lot!

**Comment by sefirothmorpheus** [comment]
i need to download some books from calameo. any working code, please?

**Comment by asvt** [comment]
I haven't find. If you find a solution, please share it 😉

**Comment by ComFoxx** [comment]
Tell me if the issue has been correctly fixed, I've deployed the GitHub Pages
https://comfoxx.github.io/calameo-download-pdf/

**Comment by asvt** [comment]
Thank you !!!! There are some errors with a calameo (I can't post its link in public) but your new code can be used correctly for the most part

**Comment by sefirothmorpheus** [comment]
it does not work (i have tried both firefox and chrome)

https://www.calameo.com/read/004822953bfbc87aa6fac

**Comment by asvt** [comment]
There is another change: https://www.calameo.com/read/00482295360bf5c24ca15 : This link was functional on Saturday but indeed it is no longer today. Other links (like in the comment above) announce an error from the start.

**Comment by ComFoxx** [comment]
well it seems like Calaméo now blocks the requests, and I've somehow made it worse by changing the cors proxy
I need a server to fake a legitimate request, but I think it is not possible with GitHub Pages

**Comment by asvt** [comment]
Would using only the local version be a solution?

**Comment by Deepou1** [comment]
Hello,
It is not working anymore I think. I tried many links and unfortunatly the web page is frozen.
I think It was working before your patch, but I am not really sure.
Is there any solution ?

Thank you very much.

**Comment by ComFoxx** [comment]
I made my own proxy
It is now hosted on my server
Can you check it is working?
I hope it will not breake like the last time

**Comment by asvt** [comment]
Cela fonctionne à nouveau pour la plupart, c'est nickel en espérant que cela dure autant que la première version ;o)
**Merci !**

(Si tu cherches un nouveau défi : cela fonctionne sauf pour des cas un peu particuliers tels que https://www.calameo.com/read/0070521158b103744c0cf?authid=7nlzOxule8uV ( avec une vidéo en premiere page ou une authentification dans l'url) , cela bloque sur le message "Chargement des paramètres du document calemeo…"))

**Comment by ComFoxx** [comment]
Même ce dernier lien fonctionne de mon côté 🤔

**Comment by asvt** [comment]
Je viens de tester, effectivement il fonctionne... Joker, je n'ai pas compris ce qui s'est passé. Tout fonctionne alors 🤘👌👍👍

**Comment by Deepou1** [comment]
Merci beaucoup !
Tout semble fonctionner correctement. Je vous préviendrai s'il y a d'autres erreurs.
Quoi qu'il en soit merci beaucoup pour votre réactivité !
